### PR TITLE
Tweaks from review.

### PR DESCRIPTION
**Pull request by mattwynne**
These are my changes from reviewing the script.

@iachettifederico I noticed that sometimes there's a line `# coding: utf-8` in the code snippets that appears out of nowhere. Do we need this? I'm not hot enough in Ruby to know the details of this. If we do need it I think we need something in the narrative that introduces it, rather than having it just appear from nowhere.

### CODE REVIEW

**Comment by mattwynne** [comment]
@sebrose I notice as I review this script that this solution is slightly different to the one we use in the workbooks. e.g. here we start with a 1-dimentional co-ordinate system, but in a class we would use a 2D one.

It would be work to change either this narrative or the workbook one. There is an opportunity here, perhaps, to bring these videos more into line with what we do in the workbooks, but that could have knock-on effects for later videos if we're not careful. I think we'd have to pair on going right the way through the code narrative to make sure.

WDYT?

**Comment by iachettifederico** [comment]
> These are my changes from reviewing the script.
> 
> @iachettifederico I noticed that sometimes there's a line `# coding: utf-8` in the code snippets that appears out of nowhere. Do we need this? I'm not hot enough in Ruby to know the details of this. If we do need it I think we need something in the narrative that introduces it, rather than having it just appear from nowhere.

I think it's necessary when you're using non ascii characters. In the original scripts there are single and double backticks. I removed them in order to make the tests pass and fixed it in the scripts, but it looks like I forgot to remove the comments on the files. I'll take care of this

**Comment by sebrose** [comment]
@mattwynne and I discussed the difference between the School script and the BDD with Cucumber workbook. I don't see the difference as a problem (because they have different intents) and we decided NOT to rewrite either the School script or the workbook.

**Comment by mattwynne** [comment]
>  I'll take care of this

Thanks @iachettifederico. I think this is good to record audio for, then.

**Comment by mattwynne** [comment]
So actually having started to record the audio, I think there are some tweaks I want to make to the lesson breaks.

**Comment by mattwynne** [comment]
Right @iachettifederico that turned out to be more than tweaks! Now I know I'm re-doing the audio I had a bit too much freedom.

Basically I changed the boundary between the fourth and fifth lessons so that there's a single video where the goal is to get the scenario to fail, then a separate one where you get it to pass.

**Pull request merged**
